apiVersion: v1
kind: Service
metadata:
  name: student-service
  labels:
    app: student-app
spec:
  type: NodePort
  selector:
    app: student-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007